import {
  ArrowUpRight,
  Circle,
  Copy,
  FlipHorizontal2,
  Hexagon,
  Layers,
  Lock,
  MousePointer2,
  Move,
  RectangleHorizontal,
  RotateCw,
  Ruler,
  Scissors,
  Slash,
  Snowflake,
  Spline,
  Type,
} from "lucide-react";
import type { ToolDefinition } from "../../../workbench/types";

/** Home-tab tools: select, draw, modify, layers, and base annotation tools. */
export const homeTechnicalRibbonTools: ToolDefinition[] = [
  {
    id: "select",
    label: "Select",
    icon: MousePointer2,
    tooltip: "Select objects",
    command: "tool.select",
    shortcut: "V",
  },
  {
    id: "line",
    label: "Line",
    icon: Slash,
    tooltip: "Draw a line segment",
    command: "draw.line",
    group: "draw",
    shortcut: "L",
  },
  {
    id: "circle",
    label: "Circle",
    icon: Circle,
    tooltip: "Draw a circle",
    command: "draw.circle",
    group: "draw",
    shortcut: "C",
  },
  {
    id: "rect",
    label: "Rect",
    icon: RectangleHorizontal,
    tooltip: "Draw a rectangle",
    command: "draw.rect",
    group: "draw",
  },
  {
    id: "arc",
    label: "Arc",
    icon: Spline,
    tooltip: "Draw an arc",
    command: "draw.arc",
    group: "draw",
  },
  {
    id: "poly",
    label: "Poly",
    icon: Hexagon,
    tooltip: "Draw a polygon",
    command: "draw.poly",
    group: "draw",
  },
  {
    id: "move",
    label: "Move",
    icon: Move,
    tooltip: "Move objects",
    command: "modify.move",
    group: "modify",
    shortcut: "M",
  },
  {
    id: "copy",
    label: "Copy",
    icon: Copy,
    tooltip: "Copy objects",
    command: "modify.copy",
    group: "modify",
  },
  {
    id: "rotate",
    label: "Rotate",
    icon: RotateCw,
    tooltip: "Rotate objects",
    command: "modify.rotate",
    group: "modify",
  },
  {
    id: "mirror",
    label: "Mirror",
    icon: FlipHorizontal2,
    tooltip: "Mirror objects",
    command: "modify.mirror",
    group: "modify",
  },
  {
    id: "trim",
    label: "Trim",
    icon: Scissors,
    tooltip: "Trim objects",
    command: "modify.trim",
    group: "modify",
  },
  {
    id: "layers",
    label: "Layers",
    icon: Layers,
    tooltip: "Layer properties",
    command: "layer.props",
    group: "layers",
  },
  {
    id: "freeze",
    label: "Freeze",
    icon: Snowflake,
    tooltip: "Freeze layer",
    command: "layer.freeze",
    group: "layers",
  },
  {
    id: "lock",
    label: "Lock",
    icon: Lock,
    tooltip: "Lock layer",
    command: "layer.lock",
    group: "layers",
  },
  {
    id: "text",
    label: "Text",
    icon: Type,
    tooltip: "Single-line text",
    command: "annotate.text",
    group: "annotate",
  },
  {
    id: "dim",
    label: "Dim",
    icon: Ruler,
    tooltip: "Dimension",
    command: "annotate.dim",
    group: "annotate",
  },
  {
    id: "leader",
    label: "Leader",
    icon: ArrowUpRight,
    tooltip: "Leader",
    command: "annotate.leader",
    group: "annotate",
  },
];
