#!/usr/bin/env bun
/**
 * Scaffold a layout preset skeleton: a coherent LayoutPreset module with a
 * registration function. Wiring it into the router preview table stays an
 * explicit manual step (documented in the output).
 */
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  bool,
  type CommandSpec,
  fail,
  type ParsedArgs,
  parseArgs,
  printHelpIfRequested,
  str,
} from "./_lib/cli";
import {
  exists,
  findRepoRoot,
  refreshAiContextIfAvailable,
} from "./_lib/files";
import {
  normalizeExtensionId,
  toCamel,
  toPascal,
  toTitle,
} from "./_lib/naming";
import { renderTree } from "./_lib/templates";

const SCRIPT = "generate:preset";

const spec: CommandSpec = {
  name: "generate:preset",
  description: "Scaffold a coherent LayoutPreset module with registration.",
  positionals: ["name"],
  flags: [
    {
      name: "label",
      description: "Preset label (default: Title Case of name)",
    },
    { name: "force", description: "Overwrite existing files", boolean: true },
    { name: "dry-run", description: "Report without writing", boolean: true },
  ],
};

const PRESET_TS = `import { globalPresets } from "../../workbench/layouts";
import type { LayoutPreset } from "../../workbench/types";

/**
 * {{LABEL}} preset: slim toolbar over a plain workspace with a status bar.
 * Declares composition only; domain content comes from registered commands,
 * tools, widgets, and status items. Adjust slots/defaultFeatures, keeping
 * every default feature hosted by a slot. Most presets keep "viewport"
 * load-bearing; viewport-free presets declare their own loadBearing
 * (e.g. forms/settings use "form", records uses "data-table") via the
 * optional LayoutPreset.loadBearing field.
 */
export const {{CAMEL}}Preset: LayoutPreset = {
  id: "{{ID}}",
  label: "{{LABEL}}",
  description: "{{LABEL}} layout generated by bun run generate:preset.",
  slots: {
    top: ["toolbar"],
    left: [],
    center: ["viewport"],
    right: [],
    bottom: ["status-bar"],
  },
  defaultFeatures: ["toolbar", "viewport", "statusbar"],
};

export function register{{PASCAL}}Preset(): void {
  if (!globalPresets.has({{CAMEL}}Preset.id)) {
    globalPresets.registerPreset({{CAMEL}}Preset);
  }
}
`;

function main(): void {
  const argv = process.argv.slice(2);
  if (
    printHelpIfRequested(argv, SCRIPT, spec, [
      "bun run generate:preset -- custom-layout",
    ])
  ) {
    return;
  }
  let parsed: ParsedArgs;
  try {
    parsed = parseArgs(argv, spec);
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error));
  }
  const rawName = parsed.positionals[0];
  if (!rawName) {
    fail(
      "Missing preset <name>. Example: bun run generate:preset -- custom-layout.",
    );
  }
  const id = normalizeExtensionId(rawName, "preset");
  const repoRoot = findRepoRoot(dirname(fileURLToPath(import.meta.url)));
  const label = str(parsed, "label") ?? toTitle(id);
  const vars = {
    ID: id,
    LABEL: label,
    CAMEL: toCamel(id),
    PASCAL: toPascal(id),
  };
  const tree: Record<string, string> = {
    [`src/features/${id}/${toCamel(id)}Preset.ts`]: PRESET_TS,
  };
  const force = bool(parsed, "force");
  const dryRun = bool(parsed, "dry-run");
  if (!dryRun && !force && exists(join(repoRoot, `src/features/${id}`))) {
    fail(`"src/features/${id}" already exists. Pass --force to replace it.`);
  }
  const results = renderTree(tree, vars, { dest: repoRoot, force, dryRun });
  for (const result of results) {
    console.log(`${result.status}: ${result.path}`);
  }
  if (dryRun) {
    return;
  }
  console.log(`Preset "${id}" scaffolded. Next:`);
  console.log(
    `  1. Call register${toPascal(id)}Preset() from the ${id} feature entry.`,
  );
  console.log(
    `  2. Add "${id}" to presetComponents in src/app/router.tsx for preview.`,
  );
  console.log(
    `  3. In a derived project, prefer \`bun run generate:add-preset -- --from <boilerplate-dir> --preset <id>\` to copy an existing boilerplate preset with full wiring instead of this empty skeleton.`,
  );
  refreshAiContextIfAvailable(repoRoot);
}

try {
  main();
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
}
